name: Build/Release

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build/Release Electron App
        uses: samuelmeuli/action-electron-builder@v1
        id: build
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: true
          build_script_name: build

      - name: Upload Setup Executable
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: poe-pricer-setup
          path: release/*.exe
